### ISSUE TITLE
Visual Studio for Mac is unavailable

### ISSUE THREAD

**Issue by Logboy2000** [RoootTheFox/celeste-ios#1]
You should update your instructions as it was discontinued and can no longer be used.

**Comment by RoootTheFox** [comment]
Oh well, that's a bummer. I don't know where else to get the required toolchains to build a dotnet Xamarin.iOS based app for iOS, if not from Microsoft - I'll look into it later, its been a while since I touched this project lmao

**Comment by Logboy2000** [comment]
I just came back to this and found a download link for it on this page:

https://learn.microsoft.com/en-us/visualstudio/mac/what-happened-to-vs-for-mac
