### ISSUE TITLE
cant run ./build.sh

### ISSUE THREAD

**Issue by Ibraheemraad1** [RoootTheFox/celeste-ios#15]
when i try to run ./build.sh it shows this error 
(error) unhandled error at line 77!
(error) THIS IS MOST LIKELY A BUG

**Comment by hmcneill46** [comment]
Hey sorry, not a dev here but I have put together a more detailed readme ( that I just happened to be working on right now ), could you have a look at that and see if it helps 
https://github.com/hmcneill46/celeste-ios/tree/in-depth-README-instructions

**Comment by hmcneill46** [comment]
Let me know if that helps :)

**Comment by hmcneill46** [comment]
starting from scratch? strange, is everything up to date, macOS, Xcode etc? but again I'm not a dev, just commenting because doing everything in that readme works for me (and someone else I was chatting to)

**Comment by Ibraheemraad1** [comment]
oh i figured it out use 
`brew install coreutils`
so you can use realpath command

**Comment by Ibraheemraad1** [comment]
also @hmcneill46 does this guide work with pirated versions? its not working for me
(error) your game install seems to be invalid (no Celeste.exe was found)
        please make sure you pointed to the correct directory.

**Comment by hmcneill46** [comment]
Just buy the game, it's from a small developer and it's a great game. After that follow my README to download the correct files that you'll need

**Comment by Ibraheemraad1** [comment]
@hmcneill46 I already bought it before on ps so I will not buy it again and I think i found a way to make it work with pirated copies but it shows a "failed to apply patch error" is this related to it being pirated?

**Comment by hmcneill46** [comment]
@Ibraheemraad1 just buy the game again, if you must you can grab it from somewhere like this for really cheap https://www.cdkeys.com/celeste-pc-steam, You'll need to then download the linux game files, which I detailed how to do in the readme I liked

**Comment by RoootTheFox** [comment]
this repo does not and will never support pirated celeste versions. please also don't link to unauthorized sellers or sites where you can buy Celeste for cheaper (or get it for free), as that causes the devs to not get money - if you want to get it for cheaper, wait for a Steam sale.

that being said, pirated versions are often modified/had their code altered, and therefore can't be supported by this project anyways, as it expects a fully original Celeste install.

**Comment by Ibraheemraad1** [comment]
@RoootTheFox ok thx
