### ISSUE TITLE
failed to build native libraries

### ISSUE THREAD

**Issue by Ibraheemraad1** [RoootTheFox/celeste-ios#16]

**Comment by Ibraheemraad1** [comment]
./build.sh: line 351: ./updatelibs.sh: No such file or directory
(error) failed to build native libraries!
using linux steam version

**Comment by RoootTheFox** [comment]
@Ibraheemraad1 did you `git clone` the repo or did you download it as zip? if you didn't do `git clone`, building the native libs will fail
